Gdpplotter 02
UBC-MDS/gdphelper pull request #48
Opened 2022-01-19 19:42 UTC by aldojasb

Guys, I'm sending my version for the gdpplotter.

-I got problems with matplolib, and spend a lot of time learning that. It is harder compared to Altair. I could only do a very simple plot, but it's enough for this milestone.
-I updated the pyproject.toml (added numpy and matplolib as dependencies)
-I also wrote my test_gdpplotter. Apparently, it's working.

2022-01-19 21:48 UTC, gfairbro commented
Hey @aldojasb great job this looks like a fair bit of coding. I am concerned that you are inputting a dataframe from file rather than just accepting a dataframe as input to your function. I am also not sure that this function is going to be robust enough to handle the different types of aggregators (other than just province and Canada-wide) that might be found in the data. I also have to make some changes to my function to deal with these differences, for example in this dataset where there is no location, it is "Special industry aggregations". (https://open.canada.ca/data/en/dataset/9f2116fc-265a-419f-a921-2d747c039f34) @RamiroMejia This is where i think we will need categories, or else a differen column name that generalizes better than Locations

2022-01-19 21:52 UTC, gfairbro commented
Opened this issue to better capture this concern: https://github.com/UBC-MDS/gdphelper/issues/49

2022-01-19 23:20 UTC, GloriaWYY reviewed
Nice work! Same as what Gabe mentioned, this function takes a pandas DataFrame rather than read in a file. In the test function, would it be better to create a toy data frame like what Tiffany illustrated in today's lecture?

I also noticed there is a space in the test file (i.e. `test_  gdpplotter.py`) 😅

2022-01-19 23:20 UTC, GloriaWYY commented on src/gdphelper/gdpplotter.py
> +    print("database loaded")
As Gabe mentioned, this function does not need to read data from files as this is done in upstream functions. 😸

2022-01-19 23:20 UTC, GloriaWYY commented on src/gdphelper/gdpplotter.py
> +    provinces
I guess this is not needed for a function?

2022-01-19 23:20 UTC, GloriaWYY commented on src/gdphelper/gdpplotter.py
> +        plt.show()
I am a bit concerned about branch coverage for these parts - might just replace it with one `if`-`else` statement 😄

2022-01-20 07:52 UTC, RamiroMejia commented on src/gdphelper/gdpplotter.py
> +        df_grouped_region_pivoted.plot(x='REF_DATE_', y='VALUE_Canada')
@gfairbro is this `REF_DATE` what you are concerned about?

2022-01-20 07:53 UTC, RamiroMejia commented on src/gdphelper/gdpplotter.py
> +        print("checking province names: we have provinces in this dataset")
might be a good idea to use try and Raise Error

2022-01-20 07:54 UTC, RamiroMejia commented on src/gdphelper/gdpplotter.py
> +    #drawing charst according to the selected option
```suggestion
    # drawing charts according to the selected option
```

2022-01-20 07:55 UTC, RamiroMejia commented on src/gdphelper/gdpplotter.py
> +def gdpplotter(data_name, aggregation):
@aldojasb so this is going to always retrieve plots by provice/country?

2022-01-20 17:00 UTC, aldojasb commented
Thanks for the nice review, guys!! I'll fix all the points tonight. See you,

2022-01-21 04:20 UTC, gfairbro requested changes
Gonna try and see what happens when 'Request Changes' is selected here, to see if a new commit will trigger a new review!

2022-01-21 16:07 UTC, closed without merging